--- 
handlers: 
  - 
    static_files: build/\1
    upload: build/(.*\..+)$
    url: /(.*\..+)$
  - 
    static_files: build/index.html
    upload: build/index.html
    url: /.*
runtime: nodejs10
service: frontend