---
env: standard
env_variables:
  SPRING_PROFILES_ACTIVE: production
handlers:
  - script: "this field is required, but ignored"
    url: /.*
manual_scaling:
  instances: 1
runtime: java11
runtime_config:
  jdk: openjdk11
service: default
